"""
uxsp.secure — Simple Developer Workflow for UXSP

Provides a Simple high-level API for developers.
All underlying complexities (PQC hybrid encryption, chunking, replay guards,
and envelope serialization) are handled automatically behind 1-line functions.
"""

from uxsp.secure._errors import (
    SecureError,
    SecureSendError,
    SecureReceiveError,
    PeerNotFoundError,
    TypeMismatchError,
)
from uxsp.secure._package import SecurePackage
from uxsp.secure._context import (
    SecureContext,
    configure,
    get_context,
    set_identity,
    get_identity,
    register_peer,
    get_peer,
    reset_context,
    _GLOBAL_CONTEXT,
)
from uxsp.secure._identity_helpers import (
    create_identity,
    rotate_keys,
    revoke_peer,
    verify_peer_validity,
    hash_password,
    verify_password,
    export_identity_encrypted,
    import_identity_encrypted,
)
from uxsp.secure._engine import (
    _normalize_id,
    _safe_is_file,
    _resolve_package_input,
    _secure_send_payload,
    _secure_receive_payload,
)
from uxsp.secure.types import *
from uxsp.secure._dispatch import Send, Receive
from uxsp.secure._stream import SendStream, ReceiveStream
from uxsp.secure._live import (
    SendLiveSession,
    ReceiveLiveSession,
    SendLiveVoiceCall,
    ReceiveLiveVoiceCall,
    SendLiveVoice,
    ReceiveLiveVoice,
    SendVoiceCall,
    ReceiveVoiceCall,
)

__all__ = [
    "SecureError",
    "SecureSendError",
    "SecureReceiveError",
    "PeerNotFoundError",
    "TypeMismatchError",
    "SecurePackage",
    "SecureContext",
    "configure",
    "get_context",
    "set_identity",
    "get_identity",
    "register_peer",
    "get_peer",
    "reset_context",
    "create_identity",
    "rotate_keys",
    "revoke_peer",
    "verify_peer_validity",
    "hash_password",
    "verify_password",
    "export_identity_encrypted",
    "import_identity_encrypted",
    "SendVideo",
    "ReceiveVideo",
    "SendAudio",
    "ReceiveAudio",
    "SendPhoto",
    "ReceivePhoto",
    "SendImage",
    "ReceiveImage",
    "SendText",
    "ReceiveText",
    "SendDocument",
    "ReceiveDocument",
    "SendDoc",
    "ReceiveDoc",
    "SendPDF",
    "ReceivePDF",
    "SendFile",
    "ReceiveFile",
    "SendBinary",
    "ReceiveBinary",
    "SendJSON",
    "ReceiveJSON",
    "SendHTML",
    "ReceiveHTML",
    "SendArchive",
    "ReceiveArchive",
    "SendZip",
    "ReceiveZip",
    "SendVoice",
    "ReceiveVoice",
    "SendLocation",
    "ReceiveLocation",
    "SendContact",
    "ReceiveContact",
    "Send",
    "Receive",
    "SendStream",
    "ReceiveStream",
    "SendLiveSession",
    "ReceiveLiveSession",
    "SendLiveVoiceCall",
    "ReceiveLiveVoiceCall",
    "SendLiveVoice",
    "ReceiveLiveVoice",
    "SendVoiceCall",
    "ReceiveVoiceCall",
]
