"""
UXSP Native Async Support (`uxsp.aio`)

High-throughput, non-blocking asynchronous dispatchers and streaming APIs for
ASGI frameworks (FastAPI, Starlette, Quart) and WebSocket connections.
"""

from uxsp.aio.secure import (
    Receive,
    ReceiveArchive,
    ReceiveAudio,
    ReceiveBinary,
    ReceiveContact,
    ReceiveDoc,
    ReceiveDocument,
    ReceiveFile,
    ReceiveHTML,
    ReceiveImage,
    ReceiveJSON,
    ReceiveLocation,
    ReceivePDF,
    ReceivePhoto,
    ReceiveText,
    ReceiveVideo,
    ReceiveVoice,
    ReceiveZip,
    Send,
    SendArchive,
    SendAudio,
    SendBinary,
    SendContact,
    SendDoc,
    SendDocument,
    SendFile,
    SendHTML,
    SendImage,
    SendJSON,
    SendLocation,
    SendPDF,
    SendPhoto,
    SendText,
    SendVideo,
    SendVoice,
    SendZip,
)
from uxsp.aio.stream import (
    stream_receive_chunks,
    stream_send_chunks,
)

__all__ = [
    # Async Dispatchers
    "SendVideo",
    "ReceiveVideo",
    "SendAudio",
    "ReceiveAudio",
    "SendPhoto",
    "ReceivePhoto",
    "SendImage",
    "ReceiveImage",
    "SendText",
    "ReceiveText",
    "SendDocument",
    "ReceiveDocument",
    "SendDoc",
    "ReceiveDoc",
    "SendPDF",
    "ReceivePDF",
    "SendFile",
    "ReceiveFile",
    "SendBinary",
    "ReceiveBinary",
    "SendJSON",
    "ReceiveJSON",
    "SendHTML",
    "ReceiveHTML",
    "SendArchive",
    "ReceiveArchive",
    "SendZip",
    "ReceiveZip",
    "SendVoice",
    "ReceiveVoice",
    "SendLocation",
    "ReceiveLocation",
    "SendContact",
    "ReceiveContact",
    "Send",
    "Receive",
    # Async Streaming
    "stream_send_chunks",
    "stream_receive_chunks",
]
