"""
UXSP Native Async Support (`uxsp.aio`)

High-throughput, non-blocking asynchronous dispatchers and streaming APIs for
ASGI frameworks (FastAPI, Starlette, Quart) and WebSocket connections.
"""

from uxsp.aio.secure import (
    Receive,
    ReceiveArchive,
    ReceiveAudio,
    ReceiveBinary,
    ReceiveContact,
    ReceiveDoc,
    ReceiveDocument,
    ReceiveFile,
    ReceiveHTML,
    ReceiveImage,
    ReceiveJSON,
    ReceiveLocation,
    ReceivePDF,
    ReceivePhoto,
    ReceiveText,
    ReceiveVideo,
    ReceiveVoice,
    ReceiveZip,
    Send,
    SendArchive,
    SendAudio,
    SendBinary,
    SendContact,
    SendDoc,
    SendDocument,
    SendFile,
    SendHTML,
    SendImage,
    SendJSON,
    SendLocation,
    SendPDF,
    SendPhoto,
    SendText,
    SendVideo,
    SendVoice,
    SendZip,
    get_identity,
    get_peer,
    register_peer,
    reset_context,
    revoke_peer,
    rotate_keys,
    set_identity,
    verify_peer_validity,
)
from uxsp.aio.stream import (
    ReceiveStream,
    SendStream,
    stream_receive_chunks,
    stream_send_chunks,
)
from uxsp.core.identity import CardExpiredError, CardRevokedError

__all__ = [
    # Async Dispatchers
    "SendVideo",
    "ReceiveVideo",
    "SendAudio",
    "ReceiveAudio",
    "SendPhoto",
    "ReceivePhoto",
    "SendImage",
    "ReceiveImage",
    "SendText",
    "ReceiveText",
    "SendDocument",
    "ReceiveDocument",
    "SendDoc",
    "ReceiveDoc",
    "SendPDF",
    "ReceivePDF",
    "SendFile",
    "ReceiveFile",
    "SendBinary",
    "ReceiveBinary",
    "SendJSON",
    "ReceiveJSON",
    "SendHTML",
    "ReceiveHTML",
    "SendArchive",
    "ReceiveArchive",
    "SendZip",
    "ReceiveZip",
    "SendVoice",
    "ReceiveVoice",
    "SendLocation",
    "ReceiveLocation",
    "SendContact",
    "ReceiveContact",
    "Send",
    "Receive",
    "SendStream",
    "ReceiveStream",
    "set_identity",
    "get_identity",
    "register_peer",
    "get_peer",
    "reset_context",
    "rotate_keys",
    "revoke_peer",
    "verify_peer_validity",
    "CardExpiredError",
    "CardRevokedError",
    # Async Streaming
    "stream_send_chunks",
    "stream_receive_chunks",
]
