<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>UXSP.Client</RootNamespace>
    <AssemblyName>UXSP.Client</AssemblyName>
    <PackageId>SivaRaja.UXSP.Client</PackageId>
    <Title>UXSP Client SDK for .NET</Title>
    <Version>1.2.0</Version>
    <Authors>SIVA RAJA S</Authors>
    <Description>Universal Exchange Security Protocol .NET / C# Client SDK for Quantum-Resistant Hybrid Encryption</Description>
    <PackageTags>uxsp;security;quantum;encryption;cryptography;hybrid-encryption</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/SIVA-RAJA/uxsp</RepositoryUrl>
    <PackageProjectUrl>https://github.com/SIVA-RAJA/uxsp</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
  </ItemGroup>
</Project>
